use_frameworks!

target 'MobileCacheSDK_Example' do
  pod 'MobileCacheSDK', :path => '../'

  target 'MobileCacheSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
